### ISSUE TITLE
High velocities due to the PX4Flow; making everything unstable.

### ISSUE THREAD

**Issue by AlexisTM** [PX4/Flow#97]
**Type**: BUG
**Firmware**: PX4 1.6.5
**Mavros**: 0.19.0
**Flow Firmware**: Recent version from QGroundControl

We have this problem for some time now.

The PX4Flow works perfectly for some time, while it gets a position, but after a successful autonomous flight, we just let the drone on its landing position and the position (mavros/local_position/pose) goes back to 0 after some time, as expected. (Optical flow data not valid).

After 10 minutes, if we move the UAV again and the PX4Flow goes valid again, we have a huge risk of having inconsistent data. The velocities are huge (moving from -15m/s to 15m/s) in each direction and the position is messy.

It is not much reproductive, yet it happens often. 

To avoid it, we have to put the drone back on the stand directly after the flight (allow the PX4Flow to be valid again).

If it happens, we reboot the Pixhawk.

**Data example from the ~local_position/odom topic**

```
---
header: 
  seq: 3377
  stamp: 
    secs: 1455212169
    nsecs: 731849024
  frame_id: map
child_frame_id: base_link
pose: 
  pose: 
    position: 
      x: -48.317073822
      y: -55.7735214233
      z: -0.44491904974
    orientation: 
      x: -0.161708654313
      y: 0.0484552781605
      z: 0.819080020573
      w: -0.548279396073
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist: 
  twist: 
    linear: 
      x: 15.614146468
      y: -11.6929008532
      z: 6.56004177461
    angular: 
      x: -0.00865820795298
      y: 0.0182159431279
      z: -0.237499073148
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```
